import json, os

os.makedirs("data", exist_ok=True)

products = [
  {"id":"P001","name":"Classic White Oxford Shirt","category":"Shirts","price":49.99,"sale_price":None,"colors":["White","Light Blue","Pink"],"sizes":["XS","S","M","L","XL","XXL"],"stock":{"XS":5,"S":12,"M":20,"L":18,"XL":10,"XXL":4},"material":"100% Cotton","description":"A timeless Oxford shirt perfect for both casual and formal occasions.","care":"Machine wash cold, tumble dry low","rating":4.7,"reviews":134},
  {"id":"P002","name":"Slim Fit Dark Wash Jeans","category":"Jeans","price":79.99,"sale_price":64.99,"colors":["Dark Blue","Black","Grey"],"sizes":["28","30","32","34","36","38"],"stock":{"28":8,"30":15,"32":22,"34":18,"36":10,"38":5},"material":"98% Cotton, 2% Elastane","description":"Modern slim fit jeans with a comfortable stretch blend.","care":"Machine wash cold inside out","rating":4.5,"reviews":218},
  {"id":"P003","name":"Floral Wrap Midi Dress","category":"Dresses","price":89.99,"sale_price":None,"colors":["Blue Floral","Pink Floral","Black Floral"],"sizes":["XS","S","M","L","XL"],"stock":{"XS":6,"S":14,"M":16,"L":9,"XL":3},"material":"100% Viscose","description":"Elegant wrap dress with a flattering silhouette and vibrant floral print.","care":"Hand wash cold or dry clean","rating":4.8,"reviews":97},
  {"id":"P004","name":"Oversized Knit Sweater","category":"Knitwear","price":69.99,"sale_price":55.99,"colors":["Cream","Camel","Burgundy","Forest Green"],"sizes":["XS/S","M/L","XL/XXL"],"stock":{"XS/S":10,"M/L":18,"XL/XXL":7},"material":"80% Wool, 20% Polyamide","description":"Cozy oversized sweater with ribbed cuffs and hem, perfect for layering.","care":"Hand wash cold, dry flat","rating":4.6,"reviews":156},
  {"id":"P005","name":"Tailored Blazer","category":"Jackets","price":129.99,"sale_price":None,"colors":["Black","Navy","Camel","Houndstooth"],"sizes":["XS","S","M","L","XL"],"stock":{"XS":4,"S":9,"M":12,"L":8,"XL":4},"material":"65% Polyester, 35% Viscose","description":"Sharp tailored blazer that transitions seamlessly from office to evening.","care":"Dry clean only","rating":4.4,"reviews":83},
  {"id":"P006","name":"High-Waist Yoga Leggings","category":"Activewear","price":54.99,"sale_price":44.99,"colors":["Black","Navy","Charcoal","Rose"],"sizes":["XS","S","M","L","XL"],"stock":{"XS":14,"S":22,"M":26,"L":18,"XL":10},"material":"78% Nylon, 22% Spandex","description":"Squat-proof high-waist leggings with a hidden pocket and 4-way stretch.","care":"Machine wash cold, hang dry","rating":4.9,"reviews":342},
  {"id":"P007","name":"Leather Crossbody Bag","category":"Accessories","price":119.99,"sale_price":None,"colors":["Black","Tan","Burgundy"],"sizes":["One Size"],"stock":{"One Size":25},"material":"Genuine Leather","description":"Compact crossbody bag with adjustable strap and gold hardware.","care":"Wipe with damp cloth, condition regularly","rating":4.7,"reviews":76},
  {"id":"P008","name":"Linen Wide-Leg Trousers","category":"Trousers","price":74.99,"sale_price":59.99,"colors":["White","Beige","Black","Sage Green"],"sizes":["XS","S","M","L","XL","XXL"],"stock":{"XS":7,"S":13,"M":17,"L":14,"XL":8,"XXL":3},"material":"100% Linen","description":"Breezy wide-leg trousers, perfect for warm weather and beach-to-brunch outfits.","care":"Machine wash cold, iron on low","rating":4.5,"reviews":112},
  {"id":"P009","name":"Ribbed Crop Top","category":"Tops","price":29.99,"sale_price":None,"colors":["White","Black","Camel","Lilac","Sage"],"sizes":["XS","S","M","L","XL"],"stock":{"XS":18,"S":24,"M":20,"L":12,"XL":6},"material":"95% Cotton, 5% Elastane","description":"Soft ribbed crop top with a slight stretch, ideal for layering or standalone summer wear.","care":"Machine wash cold","rating":4.3,"reviews":201},
  {"id":"P010","name":"Trench Coat","category":"Coats","price":189.99,"sale_price":149.99,"colors":["Camel","Black","Navy"],"sizes":["XS","S","M","L","XL","XXL"],"stock":{"XS":3,"S":7,"M":10,"L":8,"XL":5,"XXL":2},"material":"65% Cotton, 35% Polyester","description":"Classic double-breasted trench coat with a belted waist and storm flap.","care":"Dry clean only","rating":4.8,"reviews":67},
  {"id":"P011","name":"Strappy Heeled Sandals","category":"Shoes","price":84.99,"sale_price":None,"colors":["Nude","Black","Gold"],"sizes":["36","37","38","39","40","41"],"stock":{"36":5,"37":9,"38":12,"39":10,"40":7,"41":4},"material":"Faux Leather upper, synthetic sole","description":"Elegant strappy sandals with a 7cm block heel for all-day comfort.","care":"Wipe clean with damp cloth","rating":4.2,"reviews":88},
  {"id":"P012","name":"Denim Jacket","category":"Jackets","price":89.99,"sale_price":72.99,"colors":["Light Wash","Dark Wash","Black"],"sizes":["XS","S","M","L","XL","XXL"],"stock":{"XS":6,"S":11,"M":15,"L":13,"XL":7,"XXL":3},"material":"100% Cotton Denim","description":"A wardrobe staple denim jacket with button front and chest pockets.","care":"Machine wash cold, tumble dry low","rating":4.6,"reviews":189},
  {"id":"P013","name":"Silk Cami Top","category":"Tops","price":64.99,"sale_price":49.99,"colors":["Champagne","Black","Navy","Blush"],"sizes":["XS","S","M","L","XL"],"stock":{"XS":8,"S":14,"M":16,"L":10,"XL":4},"material":"100% Silk","description":"Luxurious silk cami with adjustable straps, great for layering or going out.","care":"Hand wash cold or dry clean","rating":4.5,"reviews":93},
  {"id":"P014","name":"Pleated Mini Skirt","category":"Skirts","price":44.99,"sale_price":None,"colors":["Black","Pink","Plaid","White"],"sizes":["XS","S","M","L","XL"],"stock":{"XS":10,"S":18,"M":20,"L":14,"XL":6},"material":"Polyester blend","description":"Trendy pleated mini skirt with an elastic waistband and fun movement.","care":"Machine wash cold","rating":4.4,"reviews":147},
  {"id":"P015","name":"Chunky Knit Beanie","category":"Accessories","price":24.99,"sale_price":None,"colors":["Cream","Camel","Black","Grey","Red"],"sizes":["One Size"],"stock":{"One Size":45},"material":"100% Acrylic","description":"Super soft chunky knit beanie to keep you warm in style.","care":"Hand wash cold, dry flat","rating":4.8,"reviews":220}
]

orders = [
  {"order_id":"ORD-10021","customer":"Sarah M.","date":"2025-05-28","status":"Delivered","items":[{"product":"Floral Wrap Midi Dress","size":"M","color":"Blue Floral","qty":1,"price":89.99}],"total":97.48,"tracking":"TRK884512367","estimated_delivery":"2025-06-02","delivered_on":"2025-06-01","shipping_address":"12 Maple St, London, UK"},
  {"order_id":"ORD-10034","customer":"James K.","date":"2025-06-01","status":"Shipped","items":[{"product":"Slim Fit Dark Wash Jeans","size":"32","color":"Dark Blue","qty":1,"price":64.99},{"product":"Classic White Oxford Shirt","size":"M","color":"White","qty":1,"price":49.99}],"total":125.47,"tracking":"TRK991023445","estimated_delivery":"2025-06-07","delivered_on":None,"shipping_address":"88 King Road, Manchester, UK"},
  {"order_id":"ORD-10041","customer":"Priya S.","date":"2025-06-03","status":"Out for Delivery","items":[{"product":"High-Waist Yoga Leggings","size":"S","color":"Black","qty":2,"price":44.99}],"total":97.47,"tracking":"TRK774893201","estimated_delivery":"2025-06-07","delivered_on":None,"shipping_address":"5 Park Avenue, Berlin, DE"},
  {"order_id":"ORD-10055","customer":"Lucas B.","date":"2025-06-04","status":"Processing","items":[{"product":"Tailored Blazer","size":"L","color":"Navy","qty":1,"price":129.99}],"total":137.48,"tracking":None,"estimated_delivery":"2025-06-10","delivered_on":None,"shipping_address":"34 Rue de Lyon, Paris, FR"},
  {"order_id":"ORD-10062","customer":"Emma W.","date":"2025-06-05","status":"Confirmed","items":[{"product":"Trench Coat","size":"S","color":"Camel","qty":1,"price":149.99},{"product":"Chunky Knit Beanie","size":"One Size","color":"Cream","qty":1,"price":24.99}],"total":185.47,"tracking":None,"estimated_delivery":"2025-06-11","delivered_on":None,"shipping_address":"77 Oxford St, London, UK"},
  {"order_id":"ORD-10070","customer":"Ahmed R.","date":"2025-05-25","status":"Returned","items":[{"product":"Denim Jacket","size":"XL","color":"Light Wash","qty":1,"price":72.99}],"total":80.48,"tracking":"TRK662910847","estimated_delivery":"2025-05-31","delivered_on":"2025-05-30","return_reason":"Wrong size","refund_status":"Refund Processed","shipping_address":"9 Bay Street, Toronto, CA"},
  {"order_id":"ORD-10083","customer":"Nina F.","date":"2025-06-06","status":"Processing","items":[{"product":"Silk Cami Top","size":"S","color":"Blush","qty":1,"price":49.99},{"product":"Pleated Mini Skirt","size":"S","color":"Pink","qty":1,"price":44.99}],"total":101.47,"tracking":None,"estimated_delivery":"2025-06-13","delivered_on":None,"shipping_address":"22 Elm Close, Sydney, AU"},
  {"order_id":"ORD-10091","customer":"Tom H.","date":"2025-05-20","status":"Delivered","items":[{"product":"Oversized Knit Sweater","size":"M/L","color":"Burgundy","qty":1,"price":55.99}],"total":63.48,"tracking":"TRK554781239","estimated_delivery":"2025-05-26","delivered_on":"2025-05-25","shipping_address":"1 Castle Lane, Edinburgh, UK"},
  {"order_id":"ORD-10104","customer":"Sofia L.","date":"2025-06-06","status":"Confirmed","items":[{"product":"Leather Crossbody Bag","size":"One Size","color":"Tan","qty":1,"price":119.99}],"total":127.48,"tracking":None,"estimated_delivery":"2025-06-12","delivered_on":None,"shipping_address":"45 Sunset Blvd, Hamburg, DE"},
  {"order_id":"ORD-10117","customer":"Daniel P.","date":"2025-06-07","status":"Processing","items":[{"product":"Linen Wide-Leg Trousers","size":"M","color":"Sage Green","qty":1,"price":59.99},{"product":"Ribbed Crop Top","size":"M","color":"Sage","qty":1,"price":29.99}],"total":96.47,"tracking":None,"estimated_delivery":"2025-06-14","delivered_on":None,"shipping_address":"18 Palm Grove, Dubai, AE"}
]

faqs = [
  {"id":"F001","category":"Returns","question":"What is your return policy?","answer":"We offer a hassle-free 30-day return policy. Items must be unworn, unwashed, and in original packaging with tags attached. Sale items are eligible for exchange or store credit only. To start a return, visit our Returns Portal or contact support."},
  {"id":"F002","category":"Returns","question":"How long does a refund take?","answer":"Once we receive your returned item, refunds are processed within 3–5 business days. The amount will appear on your original payment method within 5–10 business days depending on your bank."},
  {"id":"F003","category":"Returns","question":"Can I exchange an item for a different size?","answer":"Yes! We offer free size exchanges within 30 days of purchase. Simply start an exchange request through our portal, and we'll ship the new size as soon as we receive your return."},
  {"id":"F004","category":"Shipping","question":"How long does standard shipping take?","answer":"Standard shipping typically takes 3–5 business days within the UK and EU. US and Canada orders take 7–10 business days. Express shipping (1–2 business days) is available at checkout for an additional fee."},
  {"id":"F005","category":"Shipping","question":"Do you offer free shipping?","answer":"Yes! We offer free standard shipping on all orders over £50 / €60 / $65. Orders below this threshold have a flat shipping fee of £4.99 / €5.99 / $6.99."},
  {"id":"F006","category":"Shipping","question":"Do you ship internationally?","answer":"We currently ship to 40+ countries including UK, EU, USA, Canada, Australia, and UAE. Shipping rates and delivery times vary by destination. Duties and taxes may apply for international orders."},
  {"id":"F007","category":"Tracking","question":"How do I track my order?","answer":"Once your order ships, you'll receive a confirmation email with your tracking number. You can also track your order by entering your Order ID in our chatbot or visiting the Track Order section on our website."},
  {"id":"F008","category":"Sizing","question":"How do I find my correct size?","answer":"We recommend checking our Size Guide before ordering. For tops and dresses, measure your bust, waist, and hips. For trousers and jeans, use your waist and inside leg measurement. If you're between sizes, we generally recommend sizing up for a comfortable fit."},
  {"id":"F009","category":"Sizing","question":"Do your clothes run true to size?","answer":"Most of our styles run true to size. However, some oversized styles are intentionally cut larger — this is noted on the product page. Our reviews section often includes helpful sizing feedback from customers."},
  {"id":"F010","category":"Sizing","question":"What are your size measurements in cm?","answer":"XS: Bust 80–84cm, Waist 62–66cm, Hips 86–90cm. S: Bust 84–88cm, Waist 66–70cm, Hips 90–94cm. M: Bust 88–94cm, Waist 70–76cm, Hips 94–100cm. L: Bust 94–102cm, Waist 76–84cm, Hips 100–108cm. XL: Bust 102–110cm, Waist 84–92cm, Hips 108–116cm."},
  {"id":"F011","category":"Payment","question":"What payment methods do you accept?","answer":"We accept Visa, Mastercard, American Express, PayPal, Apple Pay, Google Pay, and Klarna (buy now, pay later). All transactions are secured with SSL encryption."},
  {"id":"F012","category":"Payment","question":"Is it safe to use my credit card on your site?","answer":"Absolutely. Our website uses industry-standard SSL (256-bit) encryption and is PCI DSS compliant. We never store your full card details on our servers."},
  {"id":"F013","category":"Orders","question":"Can I cancel or modify my order?","answer":"Orders can be cancelled or modified within 1 hour of placing them. After that, the order enters processing and cannot be changed. Please contact support immediately via chat if you need to make changes."},
  {"id":"F014","category":"Orders","question":"I received the wrong item — what should I do?","answer":"We're sorry about that! Please contact our support team within 7 days with your order number and a photo of the wrong item. We'll arrange a free return and ship the correct item at no extra cost."},
  {"id":"F015","category":"Products","question":"Are your products ethically made?","answer":"Yes. We are committed to ethical sourcing and work only with factories that meet our strict standards for fair wages and safe working conditions. We are also working toward becoming fully sustainable by 2026."},
  {"id":"F016","category":"Products","question":"How do I care for delicate fabrics like silk or wool?","answer":"Silk items should be hand washed in cool water with a gentle detergent or dry cleaned. Wool should be hand washed cold or machine washed on a wool cycle and dried flat. Always check the care label on the item for specific instructions."},
  {"id":"F017","category":"Promotions","question":"Do you have a student discount?","answer":"Yes! Students get 15% off all orders through our Student Beans or UNiDAYS partnership. Simply verify your student status through either platform to receive your exclusive discount code."},
  {"id":"F018","category":"Promotions","question":"How do I use a discount code?","answer":"Enter your discount code in the 'Promo Code' field at checkout. Codes are case-insensitive, and only one code can be applied per order. Some codes may exclude sale items."},
  {"id":"F019","category":"Account","question":"How do I create an account?","answer":"Click 'Sign Up' at the top of our website, enter your email and a password, and verify your email address. Having an account lets you track orders, save your wishlist, and checkout faster."},
  {"id":"F020","category":"Account","question":"I forgot my password — how do I reset it?","answer":"Click 'Forgot Password' on the login page, enter your email address, and we'll send a reset link within a few minutes. Check your spam folder if you don't see it. The link expires after 24 hours."}
]

with open("data/products.json","w") as f:
    json.dump(products, f, indent=2)
with open("data/orders.json","w") as f:
    json.dump(orders, f, indent=2)
with open("data/faqs.json","w") as f:
    json.dump(faqs, f, indent=2)

print("✅ data/products.json  →", len(products), "products created")
print("✅ data/orders.json    →", len(orders), "orders created")
print("✅ data/faqs.json      →", len(faqs), "FAQs created")